error: align http status codes with specification
Some of the HTTP status codes have changed in the WebDriver specification,
as shown in
https://github.com/w3c/webdriver/commit/d678562e3d5f94fa71d74aeb467214bf8dd734e1.